export const projects = [
  {
    id: 1,
    pinned: true,
    name: "TodoApp",
    title: "Todo Application",
    subtitle: "React, AntD",
    about:
      "Oraginze your day, keep track of activities, sort in lists, set due dates & priorities, build a journal, save notes and more",
    live_URL: "https://mrabbani007.github.io/todolist/",
    code_URL: "",
    features: [
      "Keep track of your tasks",
      "Sort in lists, set due dates, priorities & tags",
      "View tasks in calendar",
      "Build your Journal",
      "Save Notes",
      "Check commitment on dashboard",
    ],
    build: ["React context for state management", "AntD components"],
    technologies: ["React", "NodeJS", "MongoDB", "Tailwind", "SASS"],
    mainImage: "todoApp/dashboard.png",
    images: [
      "todoApp/dashboard.png",
      "todoApp/calendar.png",
      "todoApp/lists.png",
      "todoApp/tasks.png",
      "todoApp/journal.png",
      "todoApp/notes.png",
    ],
    imageNames: ["Dashboard", "Calendar", "Lists", "Tasks", "Journal", "Notes"],
  },
  {
    id: 2,
    pinned: true,
    name: "LanguageApp",
    title: "Language Learning Application",
    subtitle: "React, Redux",
    about: "Learn languages fast and easy",
    live_URL: "https://mrabbani007.github.io/linguist/",
    code_URL: "",
    features: ["Learn", "Exercise", "Save your progress"],
    build: ["Dynamically built site", "Redux toolkit for state management"],
    technologies: ["React", "Redux", "Tailwind", "Sass", "NodeJS", "MongoDB"],
    mainImage: "languageApp/chapters.png",
    images: [
      "languageApp/home.png",
      "languageApp/chapters.png",
      "languageApp/lesson.png",
      "languageApp/exercise.png",
    ],
    imageNames: ["Home Page", "Chapters", "Lesson", "Exercise"],
  },
  {
    id: 3,
    pinned: true,
    name: "onlineStore",
    title: "Online Store",
    subtitle: "React, Nodejs, ExpressJS, MongoDB",
    about:
      "Online shopping site, browse, add to cart, checkout order, track and review",
    live_URL: "https://mrabbani007.github.io/onlineStore/",
    code_URL: "",
    features: [
      "Searh products, place and track orders, save to wish list",
      "Rate & review",
      "Supplier pages, and editor mode to add products seamlessly",
    ],
    build: ["React Context, Router, Hooks"],
    technologies: ["React", "Tailwind", "SASS", "NodeJS", "MongoDB"],
    mainImage: "onlineStore/home.png",
    images: [
      "onlineStore/home.png",
      "onlineStore/store.png",
      "onlineStore/cart.png",
      "onlineStore/orders.png",
    ],
    imageNames: ["Home Page", "Store", "Cart", "Orders"],
  },
  {
    id: 4,
    pinned: false,
    name: "Movies App",
    title: "Movies Application",
    subtitle: "React, Tailwind, MoviesAPI",
    about: "Browse movies from an API, search and filter",
    live_URL: "https://mrabbani007.github.io/moviesApp/",
    code_URL: "",
    features: ["Browse movies from an API"],
    build: ["Fetches data from API, search and filter"],
    technologies: ["React", "Tailwind", "NodeJS", "MongoDB"],
    mainImage: "moviesApp/main.png",
    images: ["moviesApp/main.png", "moviesApp/movies.png"],
    imageNames: ["Home Page", "Movies Page"],
  },
  {
    id: 5,
    pinned: false,
    name: "expenseManager",
    title: "Expense Manager",
    subtitle: "React, Tailwind",
    about: "Expense Manager",
    live_URL: "https://mrabbani007.github.io/expenseManager/",
    code_URL: "",
    features: ["Add Expenses", "View Reports"],
    build: [],
    technologies: ["React", "Tailwind", "NodeJS", "ExpressJS", "MongoDB"],
    mainImage: "expenseManager/add.png",
    images: [
      "expenseManager/home.png",
      "expenseManager/add.png",
      "expenseManager/report.png",
    ],
    imageNames: ["Home Page", "Reports", "Add Transactions"],
  },
  {
    id: 6,
    pinned: false,
    name: "travelApp",
    title: "Travel App",
    subtitle: "",
    about: "Front end page for a travel app",
    live_URL: "https://mrabbani007.github.io/travelapp/",
    code_URL: "",
    features: [],
    build: [],
    technologies: ["React", "Tailwind", "Sass"],
    mainImage: "travelApp/travelApp.png",
    images: ["travelApp/travelApp.png"],
    imageNames: ["Travel App"],
  },
];
